version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: biketaxi-postgres
    environment:
      POSTGRES_DB: biketaxi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - biketaxi-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: biketaxi-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - biketaxi-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: biketaxi-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - biketaxi-net

  booking-service:
    build: ./booking-service
    container_name: biketaxi-booking-service
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biketaxi
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - biketaxi-net

  combined-ui:
    image: nginx:alpine
    container_name: biketaxi-combined-ui
    volumes:
      - ./map-client:/usr/share/nginx/html:ro
      - ./driver-simulator:/usr/share/nginx/html/driver-simulator:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5500:80"
    networks:
      - biketaxi-net
    depends_on:
      - booking-service

volumes:
  postgres_data: 

networks:
  biketaxi-net:
    driver: bridge 